name: ci

on:
  push:
    branches:
      - '*'
      - '**/**'
      - '!develop'
      - '!main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ci
        with:
          tag: ${{ github.sha }}
          repository: hello
          dry-run: yes
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}